"""empty message

Revision ID: 1a2a7e1f57bb
Revises: 
Create Date: 2017-12-17 09:36:34.393435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2a7e1f57bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=64), nullable=True),
    sa.Column('line', sa.String(length=64), nullable=True),
    sa.Column('fromHour', sa.String(length=64), nullable=True),
    sa.Column('toHour', sa.String(length=64), nullable=True),
    sa.Column('dates', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_fromHour'), 'user', ['fromHour'], unique=False)
    op.create_index(op.f('ix_user_toHour'), 'user', ['toHour'], unique=False)
    op.create_index(op.f('ix_user_dates'), 'user', ['dates'], unique=False)
    op.create_index(op.f('ix_user_device'), 'user', ['device'], unique=False)
    op.create_index(op.f('ix_user_line'), 'user', ['line'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_line'), table_name='user')
    op.drop_index(op.f('ix_user_device'), table_name='user')
    op.drop_index(op.f('ix_user_dates'), table_name='user')
    op.drop_index(op.f('ix_user_toHour'), table_name='user')
    op.drop_index(op.f('ix_user_fromHour'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
